#!/bin/bash

MONIT_OPTS=

[ -x /usr/bin/monit ] || { stop; exit 0; }
[ -f /etc/monit/monitrc ] || { stop; exit 0; }
[ -f /etc/default/clearwater-monit ] || { stop; exit 0; }

. /etc/default/clearwater-monit
[ "$START" = "yes" ] || { stop; exit 0; }

exec /usr/bin/monit -I -c /etc/monit/monitrc $MONIT_OPTS    

exec /usr/share/clearwater/bin/issue_alarm.py "upstart" "4500.6"
